## ch7_3 다차원 배열의 형태 변경하기
np.reshape, np.transpose 등의 함수를 이용하면 다차원 배열의 형태를 원하는 대로 변경할 수 있습니다.

### np.reshape
ndarray를 원하는 형태로 지정하여 변경할 수 있습니다. 단, 이 때 변경 전과 변경 후의 다차원 배열의 원소 개수가 동일하게 유지되어야 합니다.  
ex) 3 x4 -> 2 x 6

In [3]:
import numpy as np

In [4]:
a = np.arange(1, 13, 1)

In [5]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
a.reshape([2, 6])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [7]:
a.reshape([3, 4])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
a.reshape([3, 5])

ValueError: cannot reshape array of size 12 into shape (3,5)

In [10]:
a.reshape([2, 3, 2])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

### np.transpose
np.transpose는 2차원 배열의 x축과 y축을 변경해줄 때 사용합니다. np.transpose 함수에 직접 바꾸고자 하는 축을 입력해주면 해당 축을 바꿔줍니다.

In [22]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [23]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
b = np.arange(1, 9, 1)
b = b.reshape([2, 2, 2])

In [42]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
b[1][1][0]

7

In [46]:
# b[1][0][0] -> b[0][1][0]
transposed_b = np.transpose(b, (1, 0, 2))

In [47]:
transposed_b

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

### ndarray 펼치기
np.flatten을 사용하면 다차원 배열을 1차원으로 펼칠 수 있다.

In [73]:
a = np.arange(1, 13, 1).reshape([2, 3, 2])

In [74]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [75]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 연습문제
np.reshape와 np.transpose를 사용하여 b를 아래 형태들로 만들어 보세요

In [58]:
reshape_example = np.arange(1, 13, 1)

In [59]:
reshape_example.reshape([6, 2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [60]:
reshape_example.reshape([3, 2, 2])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [64]:
transpose_example = np.arange(1, 13, 1)
transpose_example = transpose_example.reshape([2, 2, 3])

In [65]:
transpose_example

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
np.transpose(transpose_example, (1, 0, 2))

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [68]:
np.transpose(transpose_example, (1, 2, 0))

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [67]:
np.transpose(transpose_example, (2, 1, 0))

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])