## ch7_2 numpy ndarray
이번 챕터에서는 numpy에서 다차원 배열을 다루는 가장 기본인 ndarray를 직접 만들어보겠습니다.


### python list를 이용해서 ndarray 생성

In [3]:
import numpy as np

### np.zeros
0으로 채워진 ndarray 리턴

### np.ones
1로 채워진 ndarray 리턴

### np.full
특정 값으로 채워진 ndarray 리턴

### np.arange
특정 간격으로 채워진 ndarray 생성

### 연습문제
np.ones, np.zeros, np.fulls를 사용하여 아래 형태의 ndarray를 생성하시오.

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])