## ch7_4 numpy indexing, slicing
numpy ndarray도 python list와 마찬가지로 인덱싱과 슬라이싱을 지원합니다. 이 때, ndarray에서만 가능한 유용한 문법이 있으니, 이를 잘 익혀보도록 하겠습니다. 

### ndarray index
기본적으로 python list에서 index를 이용하여 접근하듯 다차원 배열의 각 원소들에 접근할 수 있습니다.

In [29]:
import numpy as np

In [30]:
a = np.arange(1, 13, 1).reshape([3, 2, 2])

In [31]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [32]:
a[0]

array([[1, 2],
       [3, 4]])

In [33]:
a[0][1]

array([3, 4])

In [34]:
a[0][1][1]

4

인덱스로 접근해서 값을 업데이트 할 수도 있습니다.

In [35]:
a[0][0][0] = 100

In [36]:
a

array([[[100,   2],
        [  3,   4]],

       [[  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,  12]]])

그리고 python과는 달리 인덱스 하나에 ,를 이어붙인 문법을 사용할 수 있습니다.

In [37]:
a[0]

array([[100,   2],
       [  3,   4]])

In [38]:
a[0, 0]

array([100,   2])

In [39]:
a[0, 0, 0]

100

### : 기호 사용해서 특정 축의 데이터 모두 선택하기
ndarray index에 : 를 사용하면 해당 축의 모든 데이터를 선택하겠다는 의미입니다.

In [10]:
a = np.arange(1, 13, 1).reshape([3, 2, 2])

In [11]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [16]:
a[:]

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [17]:
a[:, 1]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [40]:
a[1, :, 1]

array([6, 8])

In [41]:
a[:, 1, :]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [18]:
a[0, :, 1]

array([2, 4])

In [19]:
a[1, 1, :]

array([7, 8])

### slicing
python list와 비슷하게 "시작 인덱스:끝 인덱스:간격" 문법으로 슬라이싱을 할 수 있습니다.

In [54]:
slicing_example = np.arange(1, 13, 1)

In [55]:
slicing_example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
slicing_example[2:5]

array([3, 4, 5])

In [57]:
slicing_example[3:9:2]

array([4, 6, 8])

### 축 선택과 슬라이싱 같이 사용하기

In [60]:
both_example = np.arange(1, 13, 1).reshape([2, 6])

In [62]:
both_example

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [64]:
both_example[:, 3:5]

array([[ 4,  5],
       [10, 11]])

## 연습문제
인덱싱과 슬라이싱을 이용하여 아래 결과들을 출력해보세요

In [43]:
example = np.arange(1, 25, 1).reshape([2, 2, 6])

In [44]:
example

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])

In [45]:
example[:, :, 2]

array([[ 3,  9],
       [15, 21]])

In [46]:
example[1, 0, 1:4]

array([14, 15, 16])

In [47]:
example[:, :, 1:4]

array([[[ 2,  3,  4],
        [ 8,  9, 10]],

       [[14, 15, 16],
        [20, 21, 22]]])

In [48]:
example[:, :, 0:5:2]

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13, 15, 17],
        [19, 21, 23]]])

In [49]:
example[:, 1, 1:4:2]

array([[ 8, 10],
       [20, 22]])