## ch7_4 numpy indexing, slicing
numpy ndarray도 python list와 마찬가지로 인덱싱과 슬라이싱을 지원합니다. 이 때, ndarray에서만 가능한 유용한 문법이 있으니, 이를 잘 익혀보도록 하겠습니다. 

### ndarray index
기본적으로 python list에서 index를 이용하여 접근하듯 다차원 배열의 각 원소들에 접근할 수 있습니다.

In [2]:
import numpy as np

In [3]:
a = np.arange(1, 13, 1).reshape([3, 2, 2])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [6]:
a[0][1][1]

4

인덱스로 접근해서 값을 업데이트 할 수도 있습니다.

In [7]:
a[0][1][1] = 100

In [8]:
a

array([[[  1,   2],
        [  3, 100]],

       [[  5,   6],
        [  7,   8]],

       [[  9,  10],
        [ 11,  12]]])

그리고 python과는 달리 인덱스 하나에 ,를 이어붙인 문법을 사용할 수 있습니다.

In [9]:
a[0, 1]

array([  3, 100])

In [10]:
a[0, 1, 1]

100

In [14]:
a[1, 1]

array([7, 8])

### : 기호 사용해서 특정 축의 데이터 모두 선택하기
ndarray index에 : 를 사용하면 해당 축의 모든 데이터를 선택하겠다는 의미입니다.

In [25]:
a = np.arange(1, 13, 1).reshape([3, 2, 2])
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [32]:
# 6: 0, 1
# 8: 1, 1
a[1, 0, 1]

6

In [33]:
a[1, 1, 1]

8

In [34]:
a[1, :, 1]

array([6, 8])

In [17]:
a[:, 1]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [18]:
a[:, 1, 1]

array([ 4,  8, 12])

In [21]:
a[1]

array([[5, 6],
       [7, 8]])

In [20]:
a[1, :, 0]

array([5, 7])

In [22]:
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [49]:
empty_array = np.empty([2,2])

In [50]:
print(empty_array[0][0])

0.0


In [51]:
empty_array

array([[0., 0.],
       [0., 0.]])

In [44]:
np.random.random(10).reshape([2, 5])

array([[0.39621914, 0.44575918, 0.59027937, 0.40718683, 0.29205288],
       [0.65245958, 0.94333328, 0.90397367, 0.03590843, 0.89742227]])

### 연습

In [37]:
b = np.arange(1, 28, 1).reshape([3, 3, 3])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [53]:
b[:, 0, 0]

array([ 1, 10, 19])

In [54]:
b[0, :, 1]

array([2, 5, 8])

In [60]:
b[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
b[0, :, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
b[:, 1, :]

array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24]])

In [56]:
b[:, :, 2]

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

### slicing
python list와 비슷하게 "시작 인덱스:끝 인덱스:간격" 문법으로 슬라이싱을 할 수 있습니다.

### 축 선택과 슬라이싱 같이 사용하기

## 연습문제
인덱싱과 슬라이싱을 이용하여 아래 결과들을 출력해보세요

In [ ]:
example = np.arange(1, 25, 1).reshape([2, 2, 6])

In [44]:
example

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])

array([[ 3,  9],
       [15, 21]])

array([14, 15, 16])

array([[[ 2,  3,  4],
        [ 8,  9, 10]],

       [[14, 15, 16],
        [20, 21, 22]]])

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[13, 15, 17],
        [19, 21, 23]]])

array([[ 8, 10],
       [20, 22]])