## ch7_5 numpy 연산
numpy ndarray도 더하고 빼기 연산을 할 수 있습니다.

### ndarray와 숫자 (스칼라값) 간의 연산
ndarray는 숫자와 더하기, 빼기, 나누기, 곱하기가 가능합니다. 이 때, ndarray의 모든 요소들에 해당 숫자 연산이 적용됩니다.

In [1]:
import numpy as np

In [3]:
a = np.arange(1, 13, 1).reshape([2, 2, 3])

In [4]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [5]:
a + 2

array([[[ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14]]])

In [6]:
a - 2

array([[[-1,  0,  1],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [7]:
a * 2

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]])

In [8]:
a / 2

array([[[0.5, 1. , 1.5],
        [2. , 2.5, 3. ]],

       [[3.5, 4. , 4.5],
        [5. , 5.5, 6. ]]])

### ndarray 간 연산
차원이 동일한 ndarray 간에는 사칙 연산이 가능합니다. 이 때는 ndarray의 동일한 인덱스끼리 연산을 수행합니다.

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([9, 10, 11])

In [14]:
a

array([[1, 2],
       [3, 4]])

In [15]:
b

array([[5, 6],
       [7, 8]])

In [16]:
c

array([ 9, 10, 11])

In [11]:
a + b

array([[ 6,  8],
       [10, 12]])

In [12]:
a - b

array([[-4, -4],
       [-4, -4]])

In [13]:
a * b

array([[ 5, 12],
       [21, 32]])

In [17]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [18]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [19]:
b + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

### numpy boolean 연산
ndarray에 부등식 연산을 수행하면 각 원소에 대해서 부등식을 만족하는지 여부를 boolean 값으로 채워준 ndarray를 리턴합니다.

In [57]:
a = np.arange(1, 13, 1).reshape([2, 2, 3])

In [58]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
a > 5

array([[[False, False, False],
        [False, False,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [60]:
a == 10

array([[[False, False, False],
        [False, False, False]],

       [[False, False, False],
        [ True, False, False]]])

이렇게 구한 boolean 값으로 채워진 ndarray는 인덱스처럼 사용할 수 있습니다.

In [65]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

혹은 np.where를 사용하면 True인 값의 인덱스를 구할 수 있습니다.

In [67]:
np.where(a>5)

(array([0, 1, 1, 1, 1, 1, 1]),
 array([1, 0, 0, 0, 1, 1, 1]),
 array([2, 0, 1, 2, 0, 1, 2]))

In [68]:
np.where(a%2==0)

(array([0, 0, 0, 1, 1, 1]),
 array([0, 1, 1, 0, 1, 1]),
 array([1, 0, 2, 1, 0, 2]))

np.where를 통해 구한 값을 다시 인덱스로 사용할 수도 있다.

In [70]:
a[np.where(a%2==0)]

array([ 2,  4,  6,  8, 10, 12])

### ndarray 간의 행렬연산

In [26]:
a = np.arange(1, 9, 1).reshape([2, 4])
b = np.arange(10, 18, 1).reshape([4, 2])

In [21]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
b

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [28]:
np.matmul(a, b)

array([[140, 150],
       [348, 374]])

### ndarray 선형대수 연산
- numpy에서 이런 것도 해주는구나 정도로 살펴보고 넘어가면 됩니다.

In [29]:
a = np.array([[1, 2], [3, 4]])

In [30]:
a

array([[1, 2],
       [3, 4]])

역행렬  구하기

In [31]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

고유값, 고유벡터 구하기

In [32]:
np.linalg.eig(a)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

특이값 분해

In [36]:
np.linalg.svd(a)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

### numpy를 이용한 기초 통계량 계산
ndarray를 이용해서 평균, 중간값, 분산, 표준 편차 등 기초 통계량들을 구할 수 있습니다.

In [38]:
a = np.array([0.5, 2, -7, 15, 3])

In [39]:
a

array([ 0.5,  2. , -7. , 15. ,  3. ])

In [40]:
np.min(a)

-7.0

In [41]:
np.max(a)

15.0

In [42]:
np.mean(a)

2.7

In [43]:
np.median(a)

2.0

In [44]:
np.var(a)

50.160000000000004

In [45]:
np.std(a)

7.0823724838503095

## 연습문제
다양한 numpy 연산을 이용해서 아래 결과를 출력해보세요

In [47]:
a = np.arange(1, 19, 2).reshape([3, 3])
b = np.arange(1, 28, 3).reshape([3, 3])

In [48]:
a

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [49]:
b

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [52]:
(a+1)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [54]:
a + b

array([[ 2,  7, 12],
       [17, 22, 27],
       [32, 37, 42]])

In [53]:
(b * 2) - a

array([[ 1,  5,  9],
       [13, 17, 21],
       [25, 29, 33]])

In [55]:
np.matmul(a, b)

array([[126, 153, 180],
       [306, 387, 468],
       [486, 621, 756]])