## ch7_3 다차원 배열의 형태 변경하기
np.reshape, np.transpose 등의 함수를 이용하면 다차원 배열의 형태를 원하는 대로 변경할 수 있습니다.

### np.reshape
ndarray를 원하는 형태로 지정하여 변경할 수 있습니다. 단, 이 때 변경 전과 변경 후의 다차원 배열의 원소 개수가 동일하게 유지되어야 합니다.  
ex) 3 x4 -> 2 x 6

In [5]:
import numpy as np

In [6]:
a = np.arange(1, 13, 1)

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
a.reshape([2, 6])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
a.reshape([2, 2, 3])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [10]:
a.reshape([4, 3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
a.reshape([4, 2])

ValueError: cannot reshape array of size 12 into shape (4,2)

### np.transpose
np.transpose는 2차원 배열의 x축과 y축을 변경해줄 때 사용합니다. np.transpose 함수에 직접 바꾸고자 하는 축을 입력해주면 해당 축을 바꿔줍니다.

In [40]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [41]:
a[1][1]

5

In [42]:
a[1][2]

6

In [43]:
at = a.transpose()

In [44]:
at, at.shape

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 (3, 2))

In [45]:
c = np.array([[1, 2], [3, 4]])

In [49]:
c[1][0]

3

In [46]:
c

array([[1, 2],
       [3, 4]])

In [47]:
c.transpose()

array([[1, 3],
       [2, 4]])

In [56]:
b = np.arange(1, 9, 1)
b = b.reshape([2, 2, 2])

In [57]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [58]:
b.shape

(2, 2, 2)

In [50]:
b[1][0][0]

5

In [51]:
# 1, 0, 0
# -> 0, 1, 0

In [62]:
bt = np.transpose(b, (2, 1, 0))

In [63]:
bt

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [55]:
bt[0][1][0]

3

In [32]:
bt[0][1][0]

5

### ndarray 펼치기
np.flatten을 사용하면 다차원 배열을 1차원으로 펼칠 수 있다.

In [38]:
a = np.arange(1, 13, 1).reshape([2, 3, 2])
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [39]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 연습문제
np.reshape와 np.transpose를 사용하여 b를 아래 형태들로 만들어 보세요

In [79]:
import numpy as np

reshape_example = np.arange(1, 13, 1)

In [80]:
reshape_example

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
# 6, 2
reshape_example.reshape([6, 2])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [83]:
# 3, 2, 2
reshape_example.reshape([3, 2, 2])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [84]:
transpose_example = np.arange(1, 13, 1)
transpose_example = transpose_example.reshape([2, 2, 3])

In [85]:
transpose_example

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [86]:
transpose_example.transpose([0, 2, 1])

array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

In [87]:
transpose_example.transpose([1, 0, 2])

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [88]:
transpose_example.transpose([1, 2, 0])

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [89]:
transpose_example.transpose([2, 0, 1])

array([[[ 1,  4],
        [ 7, 10]],

       [[ 2,  5],
        [ 8, 11]],

       [[ 3,  6],
        [ 9, 12]]])

In [90]:
transpose_example.transpose([2, 1, 0])

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [68]:
# 0, 1, 0 -> 1, 0, 0
np.transpose(transpose_example, (1, 0, 2))

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

In [72]:
# 0, 0, 2
# -> 0, 2, 0
np.transpose(transpose_example, (0, 2, 1))

array([[[ 1,  4],
        [ 2,  5],
        [ 3,  6]],

       [[ 7, 10],
        [ 8, 11],
        [ 9, 12]]])

In [91]:
np.transpose(transpose_example, (2, 1, 0))

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])