## ch7_2 numpy ndarray
이번 챕터에서는 numpy에서 다차원 배열을 다루는 가장 기본인 ndarray를 직접 만들어보겠습니다.


### python list를 이용해서 ndarray 생성

In [3]:
import numpy as np

In [7]:
np_1d = np.array([1, 2, 3, 4])

In [13]:
np_nums, type(np_nums)

(array([1, 2, 3, 4]), numpy.ndarray)

In [14]:
np_1d.shape

(4,)

In [9]:
np_2d = np.array([
    [1, 2],
    [3, 4]
])

In [15]:
np_2d, type(np_2d)

(array([[1, 2],
        [3, 4]]),
 numpy.ndarray)

In [16]:
np_2d.shape

(2, 2)

### np.zeros
0으로 채워진 ndarray 리턴

In [25]:
zeros = np.zeros([4])

In [26]:
zeros

array([0., 0., 0., 0.])

In [27]:
zeros.shape

(4,)

In [28]:
zeros = np.zeros([2, 2])

In [29]:
zeros

array([[0., 0.],
       [0., 0.]])

In [30]:
zeros.shape

(2, 2)

### np.ones
1로 채워진 ndarray 리턴

In [17]:
ones = np.ones([2, 2])

In [18]:
ones

array([[1., 1.],
       [1., 1.]])

In [21]:
ones = np.ones([3, 2, 2])

In [22]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

### np.full
특정 값으로 채워진 ndarray 리턴

In [31]:
fulls = np.full((3, 2), 7)

In [32]:
fulls

array([[7, 7],
       [7, 7],
       [7, 7]])

In [33]:
fulls.shape

(3, 2)

### np.arange
특정 간격으로 채워진 ndarray 생성

In [39]:
intervals = np.arange(1, 10, 2)

In [41]:
intervals

array([1, 3, 5, 7, 9])

### 연습문제
np.ones, np.zeros, np.fulls를 사용하여 아래 형태의 ndarray를 생성하시오.

In [35]:
np.ones([2, 2, 2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [38]:
np.zeros([3, 2, 2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [34]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [42]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])