## ch7_5 numpy 연산
numpy ndarray도 더하고 빼기 연산을 할 수 있습니다.

### ndarray와 숫자 (스칼라값) 간의 연산
ndarray는 숫자와 더하기, 빼기, 나누기, 곱하기가 가능합니다. 이 때, ndarray의 모든 요소들에 해당 숫자 연산이 적용됩니다.

In [1]:
import numpy as np

### ndarray 간 연산
차원이 동일한 ndarray 간에는 사칙 연산이 가능합니다. 이 때는 ndarray의 동일한 인덱스끼리 연산을 수행합니다.

### numpy boolean 연산
ndarray에 부등식 연산을 수행하면 각 원소에 대해서 부등식을 만족하는지 여부를 boolean 값으로 채워준 ndarray를 리턴합니다.

이렇게 구한 boolean 값으로 채워진 ndarray는 인덱스처럼 사용할 수 있습니다.

혹은 np.where를 사용하면 True인 값의 인덱스를 구할 수 있습니다.

np.where를 통해 구한 값을 다시 인덱스로 사용할 수도 있다.

### ndarray 간의 행렬연산

### ndarray 선형대수 연산
- numpy에서 이런 것도 해주는구나 정도로 살펴보고 넘어가면 됩니다.

역행렬  구하기

고유값, 고유벡터 구하기

특이값 분해

## 통계학 기본 개념

### 통계학 용어 정리 
모집단(population): 관심의 대상이 되는 전체

표본(sample): 모집단의 특성을 알기 위해 추출한 일부

통계적 추론(inference): 표본의 특징을 통해 전체 에 대한 추론을 하는 것

오차(error): 표본을 통해 얻은 정보로 모집단의 특성을 예측한 결과과 실제 모집단의 특성과 차이 나는 정도

통계학: 오차에 대한 학문, 표본에서 얻은 정보를 모집단에서의 정보로 바꾸는 과정에서 오차를 줄이는 방법을 연구. 필연적으로 수반되는 오차의 크기를 계산하여 정보 이용자나 의사 결정자에게 제공

수치 기술 통계: 숫자를 이용하여 자료의 정보를 요약하여 기술하는 것. 자료의 평균이나 표준 편차, 공분산이나 상관계수 등의 계산값을 기술 통계량이라고 한다.

### 평균
자료의 합을 자료의 개수로 나눠준 값. 모집단의 평균인지, 표본 집단의 평균인지에 따라서 표기 방법만 살짝 다르다. 헷갈린다면 표본 평균, 표본 분산 정도만 이해하고 넘어가도 무방하다.

모평균: 그리스어로 M을 나타내는 μ(뮤) 문자를 사용. N은 모집단의 수  

$$\mu=\frac{\sum_{i=1}^{n}{x_{i}}}{N}$$

표본 평균: X위에 바를 그린 기호로 표현. n은 표본의 크기

$$\bar{X}=\frac{\sum_{i=1}^{n}{x_{i}}}{n}$$

### 분산, 표준편차
자료가 평균을 기준으로 얼만큼 퍼져있는지를 측정한 값. 모든 자료들이 평균으로부터 얼만큼 떨어졌는지 거리를 제곱한 것을 평균낸 것이 분산. 분산을 제곱근 한 것이 표준 편차. 통계학은 분산의 마법이라고 불릴만큼 분산은 통계학에서 중요한 개념

모분산: 모표준편차의 제곱으로 표현됨. 각 자료 값들에서 모평균을 빼준 값의 제곱합을 다시 평균낸 값.

$$\sigma^2=\frac{\sum_{i=1}^{N}({x_{i}-\mu)^2}}{N}$$

모표준편차: 그리스어 문자료 s를 나타내는 σ를 기호로 사용. 모분산의 제곱근

$$\sigma=\sqrt{\sigma^2}$$

모집단 {1, 2, 3, 4, 5}의 표본 분산 예시)
$$\frac{(1-3)^2+(2-3)^2+(3-3)^2+(4-3)^2+(5-3)^2}{5}=2.0$$

표본 분산: 표본 표준편차의 제곱으로 표현. 표본의 수 n이 아닌, n-1로 나눠주는데 이는 통계학에서 부르는 자유도(degree of freedom)이라는 개념이다. 완벽히 이해하려면 매우 복잡한 개념으로 일단은 암기하고, 직관적으로는 각 표본들에서 표본 평균을 한번씩 빼준걸 개수에 반영시켜 준다는 의미로 받아들이면 된다.

$$s^2=\frac{\sum_{i=1}^{n}({x_{i}-\bar{x})^2}}{n-1}$$

표본 표준 편차: s로 표현
$$s=\sqrt{s^2}$$

표본 집단 {1, 2, 3, 4, 5}의 표본 분산 예시)
$$\frac{(1-3)^2+(2-3)^2+(3-3)^2+(4-3)^2+(5-3)^2}{5-1}=2.5$$

## 연습문제
다양한 numpy 연산을 이용해서 아래 결과를 출력해보세요

In [47]:
a = np.arange(1, 19, 2).reshape([3, 3])
b = np.arange(1, 28, 3).reshape([3, 3])

In [48]:
a

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [49]:
b

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

array([[ 2,  7, 12],
       [17, 22, 27],
       [32, 37, 42]])

array([[ 1,  5,  9],
       [13, 17, 21],
       [25, 29, 33]])

array([[126, 153, 180],
       [306, 387, 468],
       [486, 621, 756]])